name: Main

on:
  push:
    branches:
      - main

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@5.0
        with:
          lein: 2.9.8

      - name: Unit tests
        run: lein test

      - name: Lint
        run: lein clj-kondo --lint src

  bump-version:
    needs: test-and-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Increment patch and push
        run: |
          git config --global user.name "GitHub Actions CI"
          git config --global user.email "version.bump@users.noreply.github.com"
          pip install bumpversion
          bumpversion patch
          git push origin main
