name: Main

on:
  push:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@10.1
        with:
          cli:  1.11.1.1208
          clj-kondo: 2022.12.10

      - name: Lint
        run: clj-kondo --lint src test deps.edn

      - name: Unit tests
        run: clojure -X:test

  bump-version:
    permissions:
      contents: write
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Increment patch and push
        run: |
          git config --global user.name "GitHub Actions CI"
          git config --global user.email "version.bump@users.noreply.github.com"
          pip install bumpversion
          bumpversion patch
          git push origin main
