name: Main

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Increment patch and push
        run: |
          git config --global user.name "GitHub Actions CI"
          git config --global user.email "version.bump@users.noreply.github.com"
          pip install bumpversion
          bumpversion patch
          git push origin main
