name: Main

on:
  push:
    branches:
      - main

jobs:
  build-native-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare java
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '22'
          distribution: 'graalvm'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: 1.11.4.1474

      - name: Native build
        run: clojure -T:build native-image && ./target/mncmd stat test/resources/multistaff_test_file.musicxml

  bump-version:
    permissions:
      contents: write
    needs: build-native-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Increment patch and push
        run: |
          git config --global user.name "GitHub Actions CI"
          git config --global user.email "version.bump@users.noreply.github.com"
          pip install bumpversion
          bumpversion patch
          git push origin main
