name: Pull request
on: [ pull_request ]
jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare java
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '22'
          distribution: 'graalvm'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: 1.11.4.1474
          clj-kondo: 2024.08.01

      - name: Lint
        run: clj-kondo --lint src test deps.edn build.clj

      - name: Unit tests
        run: clojure -X:test
